//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cena
    {
        public int CenaID { get; set; }
        public int NekretninaID { get; set; }
        public decimal Iznos { get; set; }
        public System.DateTime DatumOd { get; set; }
        public System.DateTime DatumDo { get; set; }
        public bool Aktivna { get; set; }
    
        public virtual Nekretnina Nekretnina { get; set; }
    }
}
