//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nekretnina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nekretnina()
        {
            this.Cena = new HashSet<Cena>();
        }
    
        public int NekretninaID { get; set; }
        public int ProjekatID { get; set; }
        public int KategorijaID { get; set; }
        public int StrukturaID { get; set; }
        public string Sifra { get; set; }
        public string Naziv { get; set; }
        public int Sprat { get; set; }
        public decimal Kvadratura { get; set; }
        public string Opis { get; set; }
        public bool Aktivna { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cena> Cena { get; set; }
        public virtual Kategorija Kategorija { get; set; }
        public virtual Projekat Projekat { get; set; }
        public virtual Struktura Struktura { get; set; }
    }
}
