//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projekat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Projekat()
        {
            this.Nekretnina = new HashSet<Nekretnina>();
        }
    
        public int ProjekatID { get; set; }
        public string Naziv { get; set; }
        public string Adresa { get; set; }
        public int GradID { get; set; }
        public string Opis { get; set; }
    
        public virtual Grad Grad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nekretnina> Nekretnina { get; set; }
    }
}
