//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateAdmin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Struktura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Struktura()
        {
            this.Nekretnina = new HashSet<Nekretnina>();
        }
    
        public int StrukturaID { get; set; }
        public int KategorijaID { get; set; }
        public string Naziv { get; set; }
        public string Opis { get; set; }
    
        public virtual Kategorija Kategorija { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nekretnina> Nekretnina { get; set; }
    }
}
